
---
apiVersion: uptime.facets.cloud/v1alpha1
kind: HttpCheck
metadata:
  name: httpcheck-1
spec:
  runInterval: 10s
  timeout: 10m
  url: http://prometheus-operator-prometheus.default:9090/-/healthy
  expectedStatusCode: "200"
  requestType: GET

