apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.podMonitor.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.podMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  jobLabel: {{ .Values.podMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.podMonitor.selectorLabels }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  podMetricsEndpoints:
  - port: {{ .Values.windowsExporter.metricsPortname }}
    scheme: http


