apiVersion: v1
kind: Service
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}
  labels:
    {{- include "facets-notification-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api-server-port
  selector:
    {{- include "facets-notification-controller.selectorLabels" . | nindent 4 }}
