apiVersion: v1
kind: ServiceAccount
metadata:
  name: "facets-notification-sa"
  labels:
    {{- include "facets-notification-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
