apiVersion: mongo.facets.cloud/v1alpha1
kind: Role
metadata:
  name: test-role-2
spec:
  connectionString: mongodb://root:xyz@mongodb-test.default.svc.cluster.local:27017
  database: testdb
  privileges:
  - resource:
      db: testdb
      collection: testing
    actions:
      - find
      - update
      - insert
      - remove
  # inherit roles
  dbRoles:
  - db: testdb2
    role: test-role-2