apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-audit-rest.fullname" . }}
  labels: {{ include "kube-audit-rest.labels" . | nindent 4 }}
  {{- if eq .Values.tls.mode "default" }}
  annotations:
    {{- include "kube-audit-rest.hooks.annotations" (dict "hooks" "pre-install" "resourcePolicy" "before-hook-creation" "weight" -10) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  {{- if eq .Values.tls.mode "manual" }}
  {{- with .Values.tls.manual }}
    {{- . | toYaml | nindent 2 }}
  {{- end }}
  {{- else }}
  # These are placeholders which will be patched by the post install job
  tls.crt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0="
  tls.key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
  {{- end }}
