{{- $sa := "scheduled-deployment-scaler-sa" }}
{{- $role := "scheduled-deployment-scaler-role" }}
{{- $rolebinding := "scheduled-deployment-scaler-rolebinding" }}
{{- $schedules := .Values.scalingSchedules }}
{{- range $scheduleName, $schedule := $schedules }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $scheduleName }}-cronjob"
spec:
  schedule: "{{ $schedule.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ $sa }}
          containers:
            - name: scaling-job
              image: bitnami/kubectl:1.21
              command: ["/bin/sh", "-c", "kubectl scale --replicas={{ $schedule.desiredReplicas }} deployment {{ $schedule.deployment }} -n {{ default $schedule.namespace "default" }}"]
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
{{ end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $role }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch", "get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $rolebinding }}
subjects:
- kind: ServiceAccount
  name: {{ $sa }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ $role }}
  apiGroup: rbac.authorization.k8s.io
