---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $path, $config := .Values.Config }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
