apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Release.Name }}-fluentd
  name: {{ .Release.Name }}-fluentd
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluentd
      release: fluentd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluentd
        name: {{ .Release.Name }}-fluentd
        release: fluentd
    spec:
      containers:
        - image: {{ .Values.fluentd.image.repository }}
          imagePullPolicy: {{ .Values.fluentd.imagePullPolicy }}
          name: fluentd
          env:
          - name: FLUENTD_ARGS
            value: "--no-supervisor -v"
          resources:
            limits:
              cpu: {{ .Values.fluentd.resources.limits.cpu }}
              memory: {{ .Values.fluentd.resources.limits.memory }}
          volumeMounts:
            - mountPath: /var/log/efs
              name: logs-vol-azure-files
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /host/lib
              name: libsystemddir
              readOnly: true
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/log/dumps
              name: dump-vol
      priorityClassName: {{ .Values.fluentd.priorityClass.name }}
      restartPolicy: {{ .Values.fluentd.restartPolicy }}
      serviceAccount: {{ .Release.Name }}-fluentd-view
      serviceAccountName: {{ .Release.Name }}-fluentd-view
      tolerations:
        - effect: {{ .Values.global.tolerations.effect }}
          key: {{ .Values.global.tolerations.key }}
          operator: {{ .Values.global.tolerations.operator }}
          value: {{ .Values.global.tolerations.value }}
      volumes:
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - hostPath:
            path: /usr/lib64
            type: ""
          name: libsystemddir
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/log/dumps/fluentd
            type: DirectoryOrCreate
          name: dump-vol
        - name: logs-vol-azure-files
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
  updateStrategy:
    rollingUpdate:
      maxSurge: {{ .Values.fluentd.updateStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.fluentd.updateStrategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.fluentd.updateStrategy.type }}

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ccazfile
  resources:
    requests:
      storage: {{ .Values.logsVolume.persistentVolumeClaim.storageSize }}

---
# SA
apiVersion: v1
imagePullSecrets:
{{- range .Values.fluentd.imagePullSecrets }}
  - name: {{ .name}}
{{- end }}
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Release.Name }}-fluentd-view
  namespace: default
secrets:
  - name: {{ .Release.Name }}-fluentd-view-token-9jdsx