apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: mongodb-auth-operator
    app.kubernetes.io/part-of: mongodb-auth-operator
    control-plane: controller-manager
  {{- include "mongodb-auth-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "mongodb-auth-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}