name: Package and Publish Helm Chart

on:
  workflow_dispatch:

env:
  BRANCH: gh-pages

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package and publish chart
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://get.helm.sh/helm-v3.5.1-linux-amd64.tar.gz | tar xz
          ./linux-amd64/helm package kubectl-crons
          ./linux-amd64/helm package scheduled-deployment-scaler
          ./linux-amd64/helm package windows-exporter
          ./linux-amd64/helm package facets-notification-controller
          ./linux-amd64/helm package azure-nfs-log-collector
          ./linux-amd64/helm package database-operator
          ./linux-amd64/helm package scheduled-hpa-updater
          ./linux-amd64/helm package facets-uptime-monitoring
          ./linux-amd64/helm package secret-copier
          ./linux-amd64/helm package kube-audit-rest
          ./linux-amd64/helm package mongodb-auth-operator
          mkdir -p charts
          mv *.tgz charts/
          ./linux-amd64/helm repo index charts/

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: charts
          keep_files: true
          force_orphan: false
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          branch: ${{ env.BRANCH }}
