name: Package and Publish Helm Chart

on:
  workflow_dispatch:

env:
  BRANCH: gh-pages

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://get.helm.sh/helm-v3.5.1-linux-amd64.tar.gz | tar xz
          sudo mv linux-amd64/helm /usr/local/bin/helm

      - name: Package and publish chart
        run: |
          for dir in */; do
            if [[ "$dir" != .* ]] && [[ "$dir" != "charts/" ]] && [[ -f "$dir/Chart.yaml" ]]; then
              helm package "$dir"
            fi
          done
          mkdir -p charts
          if [[ "${{ env.BRANCH }}" != "main" ]]; then
            mkdir -p "charts/${{ env.BRANCH }}"
            mv *.tgz "charts/${{ env.BRANCH }}/"
          else
           mv *.tgz charts/
          fi
          helm repo index charts/
      
      # - name: Commit and push changes
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     git config --global user.name "${{ github.actor }}"
      #     git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      #     git add ./charts/
      #     git commit -m "Updated Helm charts"
      #     git push origin main

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./charts
          keep_files: true
          force_orphan: false
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          branch: ${{ env.BRANCH }}
